[package]
name = "cypherpunk-cli"
version = "0.1.0"
authors = ["tim54000"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
