name: Tim's rusty build

on:
  push:
    paths:
      - '*'
      - '!/remailer-keys/*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2016, ubuntu-18.04]
        backend: [back-gpg]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ${{ format('cargo build --verbose --release --no-default-features --features {0}', matrix.backend) }}
      - name: Release
        uses: docker://softprops/action-gh-release
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: "/target/release/cypherpunk-cli.exe, /target/release/cypherpunk-cli"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
